/** Gource visual constants to match visual behavior. */
export const GOURCE = {
  fileDiameter: 8,
  fileRadius: 4,
  fileMoveSpeed: 5,
  dirPadding: 1.5,
  forceGravity: 10,
  minDirRadius: 1,
  userSize: 20,
  userShadowOffset: 2,
  beamDistance: 100,
  actionDistance: 50,
  personalSpaceDistance: 100,
  maxUserSpeed: 500,
  userFriction: 1,
  maxFileLag: 5,
  baseActionRate: 0.5,
  forcedActionRate: 2,
  userIdleTime: 3,
  fadeDuration: 1,
  fileNameTime: 4,
  cameraPadding: 1.1,
  backgroundColor: '#1a1a1a',
  shadowOffset: 2,
  branchWidth: 5,
} as const;
